name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: sock-shop
      COMMIT: ${{ github.sha }}
      REPO: f3lin
      IMAGE: carts
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        chmod +x scripts/git_update_tag.sh
        bash scripts/git_update_tag.sh -v patch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.GROUP }}
        password: ${{ secrets.DOCKER_PASS }}
    # Build
    - name: Build jar files
      run: ./scripts/build.sh

    # Push to dockerhub
#    - name: Push to Docker Hub
#      env:
#        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
#      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
#      with:
#        username: ${{ env.GROUP }}
#        password: ${{ secrets.DOCKER_PASS }}
#        repository: ${{ env.GROUP }}/${{ env.REPO }}
#        tag_with_ref: true
#        tag_with_sha: true
#        path: docker/carts
#        dockerfile: docker/carts/Dockerfile

