name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GROUP: f3lin
      COMMIT: ${{ github.sha }}
      DOCKER_USERNAME: f3lin
      IMAGE: carts
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'semeru'
        java-version: '8.0.422+5'

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        chmod +x scripts/git_update_tag.sh
        bash scripts/git_update_tag.sh -v patch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build  jar files & Push
      env:
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        chmod +x ./scripts/build.sh
        bash scripts/build.sh

    - name: Push to Docker Hub
      env:
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker push $GROUP/$IMAGE:$IMAGE_TAG